### ISSUE TITLE
Invalid header exception

### ISSUE THREAD

**Issue by gzydominating** [signavio/sap-sam#126]
When I run "gen = RepresentationGenerator(); s = gen.generate_bpmn_xml(model_name, model_json, model_namespace).decode("utf-8")", I get the error:
`requests.exceptions.InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: '\r\n\r\n\r\n\r\n\r\n\r\n<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n<html class="academic">\r\n\r\n\t<head xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-gb" lang="en-gb" >\r\n\r\n\r\n\r\n\t\r\n\t<meta http-equiv="content-type" content="text/html; charset=utf-8" />\r\n\t<meta name="keywords" content="signavio, web-based, process editor, modeler, bpmn, epc, epk, bpm, business process management, modeling" />\r\n\r\n\t\r\n\t\t<meta name="description" content="Oops" />\r\n\t\r\n\r\n\t\r\n\r\n\t<meta name="viewport" content="width=device-width">\r\n\t\r\n\r\n\r\n\r\n\r\n\r\n\r\n\t<meta name="version" content="18.5.2" />\r\n\t\r\n\t\t<link rel="shortcut icon" href="/images/banners/bock2.ico" type="image/x-icon"/>\r\n\t\r\n\r\n\t\r\n\r\n\r\n\r\n\t\r\n\t<title>Oops</title>\r\n\r\n\t\r\n\r\n\t\r\n\t<link rel="stylesheet" href="/templates/signavio/font/icomoon/style.css" type="text/css" />\r\n\t<link rel="stylesheet" href="/templates/signavio/font/Open_Sans/style.css" type="text/css" />\r\n\t<link rel="stylesheet" href="/templates/signavio/css/signavio.css" type="text/css" />\r\n\t\r\n\t\r\n\r\n\t\r\n\r\n\t\r\n\t\r\n\t<script type="text/javascript" src="/templates/signavio/js/jquery-3.6.0.min.js"></script>\r\n\t<script type="text/javascript" src="/templates/signavio/js/modernizr.custom.js"></script>\r\n\t<script type="text/javascript" src="/templates/signavio/js/signavio.js"></script>\r\n\r\n\t\r\n</head>\r\n<body>\r\n\t\r\n\r\n<div class="page">\r\n\t<header>\r\n\t\t<div class="inner-page">\r\n\t\t\t<a href="https://www.signavio.com/" class="btn logo svg" rel="external">\r\n\t\t\t\tSignavio\r\n\t\t\t</a>\r\n\t\t</div>\r\n\t</header>\r\n\t<div class="content">\r\n\t\t<div class="inner-page">\r\n\r\n<div>\r\n    \r\n\r\n\r\n\r\n\r\n<h1>\r\n  <b> Error:</b> Oops... the system was unable to perform the requested function\r\n</h1>\r\n\r\n<p>\r\n    \r\n    <b>Request ID:</b> 13a47e1595e64a3f8b70ec75521a7ad7\r\n</p>\r\n\r\n\r\n\r\n    \r\n\r\n\r\n    \r\n\r\n\r\n\r\n\r\n\r\n\r\n    \r\n\r\n\r\n\r\n\r\n    \r\n\r\n\r\n\r\n</div>\r\n\r\n\r\n\r\n</div>\r\n</div>\r\n<footer>\r\n    <div class="inner-page">\r\n        \r\n            \r\n                <a class="btn" href="https://cdn.signavio.com/uploads/2022/11/SAP_Signavio_Free_Academic-License_EULA_V.2.0_112022_FINAL.pdf">Standard Agreement - T&amp;C</a>\r\n                <a class="btn" href="https://www.signavio.com/privacy-statement-for-sap-bpm-signavio-academic-initiative/">Privacy</a>\r\n            \r\n        \r\n    </div>\r\n</footer>\r\n</div>\r\n\r\n\r\n\r\n\r\n\r\n</body></html>\r\n\r\n\r\n'`

So, I want to know how to solve this problem?

**Comment by dubmix** [comment]
Hello @gzydominating, I ran the code on my machine and could not reproduce the problem.
I need to ask you a few questions to help you solve this:
- Have you tried running the code with a different model from SAP-SAM?
- Are you able to log into Process Manager with the credentials in your `.conf` file?

**Comment by gzydominating** [comment]
> Hello @gzydominating, I ran the code on my machine and could not reproduce the problem. I need to ask a few questions to help you solve this:
> 
> * Have you tried running the code with a different model from SAP-SAM?
> * Are you able to log into Process Manager with the credentials in your `.conf` file?

I found the problem, but new problems again, https://academic.signavio.com cannot be registered

**Comment by gzydominating** [comment]
I changed my password to chrome's recommended random password and successfully signed up, which is weird.
