### ISSUE TITLE
Some data-sets seem to have missing header information

### ISSUE THREAD

**Issue by CC90** [signavio/sap-sam#13]
When calling `parser.parse_model_metadata()`, some of the data-sets could not be parsed on my machine, with the error message that the header information was missing. The data-sets that were affected are:

70000.csv
140000.csv
330000.csv
510000.csv
590000.csv
670000.csv
820000.csv

After removing these data-sets from the data folder, the parsing worked fine.

**Comment by TimKam** [comment]
I cannot reproduce the issue with the dataset that I have locally (and see headers in 70000.csv) @sap-dianasola can you double-check? In any case, we could add code that adds headers if they are missing to mitigate this issue.

**Comment by sap-dianasola** [comment]
Unfortunately, I cannot reproduce the issue either. @CC90, is this still an issue? If you were able to mitigate the issue with @TimKam's suggestion, it would be great if you could start a pull request.
