### ISSUE TITLE
change the default "setup folder" to "my documents" (instead of shared documents)

### ISSUE THREAD

**Issue by ccoreaSAP** [signavio/sap-sam#15]
In ImageGenerator.py, the functionction "setup_folder" currently ensures a folder "SAP-SAM" in the workspace under "shared documents". When other functions such as "generate_xml" are then called, the entire network with access to the workspace will however then get (potentially thousands) of notifications such as "model x created, model y deleted". Maybe this can be changed to setup the folder under "my documents" per default. I will try this and create a pull request if applicable

**Comment by TimKam** [comment]
Makes a lot of sense, imo. Thanks!
