### ISSUE TITLE
No Conf file is provided

### ISSUE THREAD

**Issue by ssdasgupta** [signavio/sap-sam#21]
I am getting an error in this line
https://github.com/signavio/sap-sam/blob/main/src/sapsam/ImageGenerator.py#L2

`from conf import system_instance`
However, no config file is provided. Does it have to do anything with the Signavio account?

Please point me in the right direction.

**Comment by colodenn** [comment]
You need to create a conf.py file in the root of this project.

The conf file should contain:

```python
email = 'youremail@signavio.com'
pw = 'yourpassword'
tenant_id = 'your tenant id obtained from signavio academic'
system_instance = 'https://academic.signavio.com'

**Comment by dubmix** [comment]
@TimKam I think this issue can be closed?
