### ISSUE TITLE
Rate limiting for Imagegenerator

### ISSUE THREAD

**Issue by colodenn** [signavio/sap-sam#22]
I am encountering a technical issue while attempting to convert SAP Signavio Academic models into event logs (XES) using the sap-sam Image Generator module.

I have been following the process outlined in the python notebooks (https://github.com/signavio/sap-sam/blob/main/notebooks/3_images_and_XMLs.ipynb) and utilizing the sap-sam Image Generator module (https://github.com/signavio/sap-sam/blob/main/src/sapsam/ImageGenerator.py) to convert the models. I have successfully converted approximately 50 BPMN JSON files from the CSV format to .bpmn files.
However, I am now facing an issue with the generate_xml method within the Image Generator module. After successfully converting the initial set of files, the method suddenly stops returning any output, and the conversion process halts without generating any errors or indications of failure. I have reviewed the logs and examined my code to ensure there are no obvious errors or misconfigurations.

Despite my efforts, I have not been able to identify the root cause of this issue. To provide more context, I am utilizing the SAP Signavio Academic models available at this link: https://zenodo.org/record/7012043.

**Comment by ppfeiff** [comment]
@sap-dianasola @TimKam do you have a solution for this? It seems like the Image Generator Module does not terminate. Is there a limit per user? Or does the function have no timeout?

We really would like to use all BPMN models but without converting them via the Image Generator module it seems like we are stuck here.

**Comment by TimKam** [comment]
@ppfeiff @colodenn Thanks for the `@mention`, without it I don't get a notification :-)
Can you try to artificially slow down your image generation?
Perhaps you send too many requests in a short time.

**Comment by ppfeiff** [comment]
We added a delay between requests and it sems like we are able to get more successful conversions. We will report back.
